/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/gb.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials.Material} position={[-0.05, 1.03, -0.42]} />
      <mesh
        geometry={nodes.alights014_Plane051.geometry}
        material={nodes.alights014_Plane051.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.alights000_Plane049.geometry}
        material={nodes.alights000_Plane049.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.alights015_Plane050.geometry}
        material={nodes.alights015_Plane050.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane047_Plane042.geometry}
        material={nodes.Plane047_Plane042.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane036_Plane040.geometry}
        material={nodes.Plane036_Plane040.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cube028_Cube030.geometry}
        material={nodes.Cube028_Cube030.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cube029_Cube031.geometry}
        material={nodes.Cube029_Cube031.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Icosphere001.geometry}
        material={nodes.Icosphere001.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cube027_Cube025.geometry}
        material={nodes.Cube027_Cube025.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane013_Plane014.geometry}
        material={nodes.Plane013_Plane014.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh geometry={nodes.Icosphere.geometry} material={nodes.Icosphere.material} rotation={[Math.PI / 2, 0, 0]} />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Cube048_Cube080_1.geometry} material={nodes.Cube048_Cube080_1.material} />
        <mesh geometry={nodes.Cube048_Cube080_2.geometry} material={nodes.Cube048_Cube080_2.material} />
        <mesh geometry={nodes.Cube048_Cube080_3.geometry} material={nodes.Cube048_Cube080_3.material} />
        <mesh geometry={nodes.Cube048_Cube080_4.geometry} material={nodes.Cube048_Cube080_4.material} />
        <mesh geometry={nodes.Cube048_Cube080_5.geometry} material={nodes.Cube048_Cube080_5.material} />
        <mesh geometry={nodes.Cube048_Cube080_6.geometry} material={nodes.Cube048_Cube080_6.material} />
        <mesh geometry={nodes.Cube048_Cube080_7.geometry} material={nodes.Cube048_Cube080_7.material} />
        <mesh geometry={nodes.Cube048_Cube080_8.geometry} material={nodes.Cube048_Cube080_8.material} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Cube046_Cube063_1.geometry} material={nodes.Cube046_Cube063_1.material} />
        <mesh geometry={nodes.Cube046_Cube063_2.geometry} material={nodes.Cube046_Cube063_2.material} />
        <mesh geometry={nodes.Cube046_Cube063_3.geometry} material={nodes.Cube046_Cube063_3.material} />
        <mesh geometry={nodes.Cube046_Cube063_4.geometry} material={nodes.Cube046_Cube063_4.material} />
        <mesh geometry={nodes.Cube046_Cube063_5.geometry} material={nodes.Cube046_Cube063_5.material} />
        <mesh geometry={nodes.Cube046_Cube063_6.geometry} material={nodes.Cube046_Cube063_6.material} />
        <mesh geometry={nodes.Cube046_Cube063_7.geometry} material={nodes.Cube046_Cube063_7.material} />
        <mesh geometry={nodes.Cube046_Cube063_8.geometry} material={nodes.Cube046_Cube063_8.material} />
      </group>
      <mesh
        geometry={nodes.Text001_Text002.geometry}
        material={nodes.Text001_Text002.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Cylinder026_Cylinder025_1.geometry} material={materials['red.002']} />
        <mesh geometry={nodes.Cylinder026_Cylinder025_2.geometry} material={nodes.Cylinder026_Cylinder025_2.material} />
      </group>
      <mesh
        geometry={nodes.Plane024.geometry}
        material={materials['Studio_Lights.004']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh geometry={nodes.Cube036.geometry} material={nodes.Cube036.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh
        geometry={nodes.Cylinder027_Cylinder026.geometry}
        material={materials['back_drop.004']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh geometry={nodes.Cube038.geometry} material={nodes.Cube038.material} rotation={[Math.PI / 2, 0, 0]} />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Plane014_Plane020_1.geometry} material={nodes.Plane014_Plane020_1.material} />
        <mesh geometry={nodes.Plane014_Plane020_2.geometry} material={materials.silver_trim} />
      </group>
      <mesh geometry={nodes.BezierCurve.geometry} material={materials.black_cable} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube026_Cube020.geometry} material={materials.ENGINE} rotation={[Math.PI / 2, 0, 0]} />
      <mesh
        geometry={nodes.Text002_Text001.geometry}
        material={nodes.Text002_Text001.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cube043_Cube081.geometry}
        material={nodes.Cube043_Cube081.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder034_Cylinder131.geometry}
        material={nodes.Cylinder034_Cylinder131.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Cylinder033_Cylinder126_1.geometry} material={materials.aluminiumm} />
        <mesh geometry={nodes.Cylinder033_Cylinder126_2.geometry} material={materials.glossy} />
        <mesh geometry={nodes.Cylinder033_Cylinder126_3.geometry} material={materials.white_holders} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Cube039_1.geometry} material={nodes.Cube039_1.material} />
        <mesh geometry={nodes.Cube039_2.geometry} material={nodes.Cube039_2.material} />
        <mesh geometry={nodes.Cube039_3.geometry} material={nodes.Cube039_3.material} />
        <mesh geometry={nodes.Cube039_4.geometry} material={nodes.Cube039_4.material} />
        <mesh geometry={nodes.Cube039_5.geometry} material={nodes.Cube039_5.material} />
        <mesh geometry={nodes.Cube039_6.geometry} material={nodes.Cube039_6.material} />
        <mesh geometry={nodes.Cube039_7.geometry} material={nodes.Cube039_7.material} />
        <mesh geometry={nodes.Cube039_8.geometry} material={nodes.Cube039_8.material} />
      </group>
      <mesh geometry={nodes.Plane026.geometry} material={nodes.Plane026.material} rotation={[Math.PI / 2, 0, 0]} />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Cube042_1.geometry} material={materials['headlight_glass.004']} />
        <mesh geometry={nodes.Cube042_2.geometry} material={materials['headlight_square.004']} />
      </group>
      <mesh geometry={nodes.Cube044.geometry} material={nodes.Cube044.material} rotation={[Math.PI / 2, 0, 0]} />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Plane027_1.geometry} material={materials['reflective_coat.004']} />
        <mesh geometry={nodes.Plane027_2.geometry} material={materials['glass_front.004']} />
        <mesh geometry={nodes.Plane027_3.geometry} material={materials['Trim.004']} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Plane028_1.geometry} material={materials['BLUE.002']} />
        <mesh geometry={nodes.Plane028_2.geometry} material={nodes.Plane028_2.material} />
        <mesh geometry={nodes.Plane028_3.geometry} material={nodes.Plane028_3.material} />
        <mesh geometry={nodes.Plane028_4.geometry} material={materials['front_window.004']} />
        <mesh geometry={nodes.Plane028_5.geometry} material={materials['black_fuel_tank.004']} />
        <mesh geometry={nodes.Plane028_6.geometry} material={materials['black_strip.004']} />
        <mesh geometry={nodes.Plane028_7.geometry} material={materials['WHEEL_CURB.004']} />
        <mesh geometry={nodes.Plane028_8.geometry} material={materials['black_vent.004']} />
        <mesh geometry={nodes.Plane028_9.geometry} material={materials.black_side_vent} />
        <mesh geometry={nodes.Plane028_10.geometry} material={materials.Mirrors} />
        <mesh geometry={nodes.Plane028_11.geometry} material={materials.exhaust} />
        <mesh geometry={nodes.Plane028_12.geometry} material={materials.black} />
      </group>
    </group>
  )
}

useGLTF.preload('/gb.glb')
