import Head from 'next/head';

import Test from './testContent';
import { useAppContext } from './Context';

//import Navbar from './Navbar';


const Layout = ({ children }) => {
    let popup = useAppContext();

    return (<>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="initial-scale=1.0, width=device-width" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        {children}



    </>)
}


export default Layout;
