/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useEffect } from 'react'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/final+plane3.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    console.log(actions)
    actions['Curve.003Action'].play();
    actions['Curve.004Action'].play();
    setTimeout(() => {
      actions['Curve.003Action'].stop();
      actions['Curve.004Action'].stop();
    }, 1000)
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Point" position={[-0.44, 0.35, -0.11]} rotation={[-0.07, -0.04, 0.93]}>
        <pointLight intensity={3} decay={2} color="#ff6ad2" rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group name="Spot" position={[0.06, -0.01, 0.16]}>
        <pointLight intensity={44.5} decay={2} color="#ff8f15" rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group name="Spot001" position={[-0.09, 0.83, -6.25]} rotation={[-1.01, -0.11, 0.05]}>
        <spotLight intensity={10} angle={0.3} penumbra={0.15} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <mesh
        name="Plane"
        geometry={nodes.Plane.geometry}
        material={nodes.Plane.material}
        position={[0, 0, 0.01]}
        scale={[1.11, 2.71, 1.01]}
      />
      <mesh
        name="Curve"
        geometry={nodes.Curve.geometry}
        material={materials.blue}
        position={[-0.95, 0.06, 0.74]}
        scale={5.68}
      />
      <mesh
        name="Curve001"
        geometry={nodes.Curve001.geometry}
        material={nodes.Curve001.material}
        position={[-0.95, 0.06, 0.74]}
        scale={5.68}
      />
      <mesh
        name="Curve002"
        geometry={nodes.Curve002.geometry}
        material={nodes.Curve002.material}
        position={[-0.95, 0.06, 0.74]}
        scale={5.68}
      />
      <mesh
        name="Curve003"
        geometry={nodes.Curve003.geometry}
        material={nodes.Curve003.material}
        position={[-0.95, 0.06, 0.74]}
        scale={5.68}
      />
      <mesh
        name="Curve004"
        geometry={nodes.Curve004.geometry}
        material={nodes.Curve004.material}
        position={[-0.95, 0.06, 0.74]}
        scale={5.68}
      />
    </group>
  )
}

useGLTF.preload('/final+plane3.glb')
