/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'


export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/final+plane4.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    console.log(actions)
    actions['Curve.003Action.002'].play();
    actions['Curve.004Action.002'].play();
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Spot" position={[0.06, 0.04, 0.16]}>
        <pointLight intensity={44.5} decay={2} color="#ff8f15" rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group name="Spot001" position={[-0.1, 3.31, -6.27]} rotation={[-1.01, -0.11, 0.05]}>
        <spotLight intensity={10} angle={0.3} penumbra={0.15} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <mesh
        name="Plane"
        geometry={nodes.Plane.geometry}
        material={materials['Material.001']}
        position={[0, -0.01, 0.01]}
        scale={[1.11, 2.71, 1.01]}
      />
      <mesh
        name="Curve"
        geometry={nodes.Curve.geometry}
        material={materials.blue}
        position={[-0.95, 0.11, 0.74]}
        scale={5.68}
      />
      <mesh
        name="Curve001"
        geometry={nodes.Curve001.geometry}
        material={nodes.Curve001.material}
        position={[-0.95, 0.11, 0.74]}
        scale={5.68}
      />
      <mesh
        name="Curve002"
        geometry={nodes.Curve002.geometry}
        material={nodes.Curve002.material}
        position={[-0.95, 0.11, 0.74]}
        scale={5.68}
      />
      <mesh
        name="Curve003"
        geometry={nodes.Curve003.geometry}
        material={nodes.Curve003.material}
        position={[-0.97, 0.21, 0.69]}
        scale={5.68}
      />
      <mesh
        name="Curve004"
        geometry={nodes.Curve004.geometry}
        material={nodes.Curve004.material}
        position={[-0.97, 0.21, 0.69]}
        scale={5.68}
      />
    </group>
  )
}

useGLTF.preload('/final+plane4.glb')
